In [1]:
pip install -Uqq fastbook

Note: you may need to restart the kernel to use updated packages.

In case "Add persistent_workers class variable to FakeLoader " error

please downgrade py torch version by using -> `conda install pytorch==1.6.0 torchvision==0.7.0 -c pytorch` command

* https://github.com/fastai/fastai/pull/2878
* https://github.com/lgvaz/faststyle/pull/18

In [1]:
from sklearn.metrics import classification_report

from fastai.tabular.all import *
from fastai.basics import *
from fastai import *

import numpy as np
import pandas as pd
import glob
# torch.set_num_threads(10)

In [11]:
# load the baseline model
#learn.load('TubularLearner.fastAI._stage1')
deployed_path = "/mnt/vdb/thesis/TubularLearner.V.set_9.pssm.retrain"
#deployed_path = "TubularLearner.fastAI._stage2.pth"
learner = load_learner(deployed_path)

In [12]:
learner.model

TabularModel(
  (embeds): ModuleList()
  (emb_drop): Dropout(p=0.5, inplace=False)
  (bn_cont): BatchNorm1d(400, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layers): Sequential(
    (0): LinBnDrop(
      (0): BatchNorm1d(400, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (1): Linear(in_features=400, out_features=1221, bias=False)
      (2): ReLU(inplace=True)
    )
    (1): LinBnDrop(
      (0): BatchNorm1d(1221, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (1): Linear(in_features=1221, out_features=1221, bias=False)
      (2): ReLU(inplace=True)
    )
    (2): LinBnDrop(
      (0): BatchNorm1d(1221, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (1): Linear(in_features=1221, out_features=1221, bias=False)
      (2): ReLU(inplace=True)
    )
    (3): LinBnDrop(
      (0): BatchNorm1d(1221, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (1): Linear(in_features=1221, out_features=1221, bias=False)
      (2): ReLU(inplace=True)
    )
    (4): LinBnDrop(
      (0): BatchNorm1d(1221, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (1): Linear(in_features=1221, out_features=1221, bias=False)
      (2): ReLU(inplace=True)
    )
    (5): LinBnDrop(
      (0): Linear(in_features=1221, out_features=2, bias=True)
    )
  )
)

In [13]:
df = pd.read_pickle("../datasets/truthset/pssm/AMPs.truthset.reps.pkl")
#df = pd.read_pickle("../datasets/truthset/AMPs_truthset.reps.plk")
ready_df =df[[ "reps"]]
ready_df

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       reps
0   [0.5506754102838333, 0.4850044983805899, 0.4850044983805899, 0.4850044983805899, 0.4850044983805899, 0.4850044983805899, 0.4850044983805899, 0.4850044983805899, 0.4850044983805899, 0.4850044983805899, 0.4850044983805899, 0.4850044983805899, 0.4850044983805899, 0.4850044983805899, 0.4850044983805899, 0.4850044983805899, 0.4850044983805899, 0.4850044983805899, 0.4850044983805899, 0.4850044983805899, 0.4950001666600003, 0.5169435099468573, 0.4950001666600003, 0.4950001666600003, 0.4950001666600003, 0.4950001666600003, 0.4950001666600003, 0.4950001666600003, 0.4950001666600003, 0.4950001666600...
1   [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.4829611457389907, 0.5575282030158855, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, ...
2   [0.5496883950645269, 0.4852983566307939, 0.4852983566307939, 0.4852983566307939, 0.4852983566307939, 0.4852983566307939, 0.4852983566307939, 0.4852983566307939, 0.4852983566307939, 0.4852983566307939, 0.4852983566307939, 0.4852983566307939, 0.4852983566307939, 0.4852983566307939, 0.4852983566307939, 0.4852983566307939, 0.4852983566307939, 0.4852983566307939, 0.4852983566307939, 0.4852983566307939, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, ...
3   [0.5192518413309044, 0.4943184263741699, 0.4943184263741699, 0.4943184263741699, 0.4943184263741699, 0.4943184263741699, 0.4943184263741699, 0.4943184263741699, 0.4943184263741699, 0.4943184263741699, 0.4943184263741699, 0.4943184263741699, 0.4943184263741699, 0.4943184263741699, 0.4943184263741699, 0.4943184263741699, 0.4943184263741699, 0.4943184263741699, 0.4943184263741699, 0.4943184263741699, 0.4886383197811632, 0.5384466841615564, 0.4886383197811632, 0.4886383197811632, 0.4886383197811632, 0.4886383197811632, 0.4886383197811632, 0.4886383197811632, 0.4886383197811632, 0.4886383197811...
4   [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.46778661733937166, 0.6076439431625903, 0.46778661733937166, 0.46778661733937166, 0.46778661733937166, 0.46778661733937166, 0.46778661733937166, 0.46778661733937166, 0.46778661733937166, 0.46778661733937166, 0.46778661733937166, 0.46778661733937166, 0.46778661733937166, 0.46778661733937166, 0.46778661733937166, 0.46778661733937166, 0.46778661733937166, 0.46778661733937166, 0.46778661733937166, 0.46778661733937166, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0...
..                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ...
57  [0.5575282030158855, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4829611457389907, 0.4943184263741699, 0.5192518413309044, 0.4943184263741699, 0.4943184263741699, 0.4943184263741699, 0.4943184263741699, 0.4943184263741699, 0.4943184263741699, 0.4943184263741699, 0.4943184263741...
58  [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.4843800842769844, 0.5527714837522621, 0.4843800842769844, 0.4843800842769844, 0.4843800842769844, 0.4843800842769844, 0.4843800842769844, 0.4843800842769844, 0.4843800842769844, 0.4843800842769844, 0.4843800842769844, 0.4843800842769844, 0.4843800842769844, 0.4843800842769844, 0.4843800842769844, 0.4843800842769844, 0.4843800842769844, 0.4843800842769844, 0.4843800842769844, 0.4843800842769844, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, ...
59  [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.4875026035157896, 0.4875026035157896, 0.4875026035157896, 0.5422738369387539, 0.4875026035157896, 0.4875026035157896, 0.4875026035157896, 0.4875026035157896, 0.4875026035157896, 0.4875026035157896, 0.4875026035157896, 0.4875026035157896, 0.4875026035157896, 0.4875026035157896, 0.4875026035157...
60  [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.46879062662624377, 0.6043802427882677, 0.46879062662624377, 0.46879062662624377, 0.46879062662624377, 0.46879062662624377, 0.46879062662624377, 0.46879062662624377, 0.46879062662624377, 0.46879062662624377, 0.46879062662624377, 0.46879062662624377, 0.46879062662624377, 0.46879062662624377, 0.46879062662624377, 0.46879062662624377, 0.46879062662624377, 0.46879062662624377, 0.46879062662624377, 0.46879062662624377, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0...
61  [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.4655718070254902, 0.6148122850510999, 0.4655718070254902, 0.4655718070254902, 0.4655718070254902, 0.4655718070254902, 0.4655718070254902, 0.4655718070254902, 0.4655718070254902, 0.4655718070254902, 0.4655718070254902, 0.4655718070254902, 0.4655718070254902, 0.4655718070254902, 0.4655718070254902, 0.4655718070254902, 0.4655718070254902, 0.4655718070254902, 0.4655718070254902, 0.4655718070254902, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, ...

[62 rows x 1 columns]

## Chanage format

In [14]:
df_new = ready_df.reps.apply(pd.Series).astype(np.float64)
df_new.columns = df_new.columns.astype(str)
#to = TabularPandas(df_new , cont_names =reps_columns, y_block = CategoryBlock, splits=splits)

In [15]:
df_new

,0,1,2,3,4,5,6,7,8,9,...,390,391,392,393,394,395,396,397,398,399
0,0.550675,0.485004,0.485004,0.485004,0.485004,0.485004,0.485004,0.485004,0.485004,0.485004,...,0.495000,0.495000,0.495000,0.495000,0.495000,0.495000,0.495000,0.495000,0.495000,0.516944
1,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,...,0.482961,0.482961,0.482961,0.482961,0.482961,0.482961,0.482961,0.482961,0.482961,0.557528
2,0.549688,0.485298,0.485298,0.485298,0.485298,0.485298,0.485298,0.485298,0.485298,0.485298,...,0.485298,0.485298,0.485298,0.485298,0.485298,0.485298,0.485298,0.485298,0.485298,0.549688
3,0.519252,0.494318,0.494318,0.494318,0.494318,0.494318,0.494318,0.494318,0.494318,0.494318,...,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000
4,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,...,0.475825,0.475825,0.475825,0.475825,0.475825,0.475825,0.475825,0.475825,0.475825,0.581288
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,0.557528,0.482961,0.482961,0.482961,0.482961,0.482961,0.482961,0.482961,0.482961,0.482961,...,0.494318,0.494318,0.494318,0.494318,0.494318,0.494318,0.494318,0.494318,0.494318,0.519252
58,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,...,0.494792,0.494792,0.494792,0.494792,0.494792,0.494792,0.494792,0.494792,0.494792,0.517649
59,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,...,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000
60,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,...,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000
61,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,...,0.491380,0.491380,0.491380,0.491380,0.491380,0.491380,0.491380,0.491380,0.491380,0.529191

## Predict
To get prediction on a new dataframe, you can use the test_d

In [16]:
dl = learner.dls.test_dl(df_new)
_preds,_none ,_y = learner.get_preds(dl=dl, with_decoded=True)

In [17]:
df['class'] = _y
df.drop(columns=['reps'],inplace =True)
df

,ID,paper,seq,class
0,ISGCock_Contig04_0915,PMC4864078,ALQICTRNMIDDRLPYVADNVRPGTFIKQQRKQKQQRHHTSGTRKRMAKG,1
1,ISGCock_Contig13_4610,PMC4864078,HLYPCKLNLKLGKVPFHFLNLNHKGKSIMVNQQTCLYYIICQTR,1
2,ISGCock_Contig16_2060,PMC4864078,ISHNHLTAASITHVKNRGKYIYMHLKFRKTNVLI,1
3,ISGCock_Contig16_4974,PMC4864078,RKKVWFIFHVCPKLKQRILSDTHAKNKCRLSPLLIKSTKIKNET,0
4,ISGCock_Contig07_3736,PMC4864078,CNYISFFRKCKNSQSTMYGCHRMNKCVFSSY,1
...,...,...,...,...
57,TR42258|c1_g1_i1,hal-02965337,MRYIVCFVFFLFFFLLFLWLVPARTASSFLTPRLSSLGKRSWAV,1
58,TR27534|c0_g1_i1,hal-02965337,MLFKVIIVIWISVCRECTRGGFCNFMHLKPISRELRRELYGRTRRRRK,1
59,P3,S2162-2531(20)30132-3,FWELWKFLKSLWSIFPRRRP,0
60,P10,S2162-2531(20)30132-3,ICTTLNWMVKLTCLTHVTLTTRWC,1
61,P26,S2162-2531(20)30132-3,RWPPTTTLCYLSRPRRCSWTSSVCRCTLT,0

In [18]:
len(df[df["class"] == 0] )

38

In [11]:
df[df["class"] == 1]

,ID,paper,seq,length,class
1,ISGCock_Contig13_4610,PMC4864078,HLYPCKLNLKLGKVPFHFLNLNHKGKSIMVNQQTCLYYIICQTR,44,1
2,ISGCock_Contig16_2060,PMC4864078,ISHNHLTAASITHVKNRGKYIYMHLKFRKTNVLI,34,1
6,ISGCock_Contig13_3006,PMC4864078,ANLLRHKVYGYCVLGPKGSSLGGIHGTWHDHHCSLIQRNPSTSTKGN,47,1
8,ISGCock_Contig12_4176,PMC4864078,VVGRKHSILNCIPYLKKKKIMRLVESESIG,30,1
9,ISGCock_Contig15_1337,PMC4864078,KRMKLNAKKLSFCDHLNSYLNLSPTLFIHNSSKQWSHWLWHNGIRI,46,1
56,TR36613|c0_g1_i1,hal-02965337,MKMISRKESLKAPHLSLLISMLHGVGLANYWLLVLRRLLITKKVMWF,47,1
57,TR42258|c1_g1_i1,hal-02965337,MRYIVCFVFFLFFFLLFLWLVPARTASSFLTPRLSSLGKRSWAV,44,1

Basic Check

In [12]:
df["length"].describe()

count     62.000000
mean      63.241935
std       57.188410
min        9.000000
25%       25.250000
50%       64.000000
75%       73.250000
max      267.000000
Name: length, dtype: float64

check these data exist in training set

In [23]:
#training_AMPs_df=pd.read_csv("../datasets/deduplicate/AMPS_NonAMPs.ready.csv",sep=',',header=0,quoting=csv.QUOTE_ALL)
#training_AMPs_df # Class 0= AMPs , 1=NonAMps

,ID,Sequence,length,class
0,EN92515250|C|B3FJD7|phage 201phi2-1 lysin,MAKKSVPLRKPAGSDGQGNIKVPGGPVVLDLGDFDDIFGPMESESPKQGPLGQFYTGLKDSLSDRFKTKDIVRNFLRSAAPDGISNVMGFADEAMAVTRDIKESLERTNAADLQYIAKKAQQILPQVKDYVSEDTYNNISEGLENKIDEYDYTIQSGRDQTAIRRARQEESDSNQIKAAMDNIALTERLNHNKSEQAANARHNQSRAENSIRDVLTTKRFDFMAKSMGMAVDSLQRLAGYNEQVDYGFQRKGLELQFRSYLGIKELVKLSEAHLELNARAYNSIVRNTALADHQKTNRKDLGQIGNGQSNSRGFASNAARAIGGKTLSQFYGNYSGNVQSRVTDSLSQKLGMAVQAIKMGEAGPNLWDNKYSFAGGIAGDFLSDFLLNDLVPMMGREARSPLTKLSNKYGGRHNQAGYLMDNMPAFMQEFVNNNQNQHGWKGSIRNLIAPYVPQFGLQDRLQNGTFQTIDQHAAFNQATQRSIVDAIPGYLARILQEMRMIRTGSDQVAREVFDMTTGKFGVEANMHDNIQNRILPENAVRSASATINDALNQIDKDGKLSAGARKALGERLLRDSSSNQRFDPEAYIRTRGYAQG...,2337,0
1,EN54061055|C|F8SJ56|phage PhiPA3 lysin,MASKKTTLPKPKGINPQGSIVQLDLDDFDDLFDEDFGLPKKNSPYTDFKSGLKSGFLDKFKTTTVLKNFLRHAAPDGFNRLFGVYDDLVTSAKDIKDSVERTNAADLDYLGRKAKSYLPYLEKHIPNTLYKSMDEGLSRKLEQYNYEMEAGRDQIAIRKRAQQAADENEIKAALDQNTLVSKENFQRSEQGIIKRAAMEKAERNIRDKISAGRFDFTSRAMSMAVDSLTRISAYHEQVSYGMQRKSLELQFRSYLGIRDLVRLTEANMELQDRAFQALVRNTGIPEHKKAGMGSGLLGFGDGRGNASFAKALAGAAFSTLPGFMGNWGGQVEDRVKKSLSGRLADIVSAARMGEGAGSFWDQRYNLAGMMAGEFGSDVINDHIAPWLGSKLRPGATRLAQRFGGRHNQLNYTLDNIPAFLQEFVNNSQNQYGWKGTVRDMIAPFIPQFSLKDRLDNGTYQTIDQQTAFNQLTQRSITEVIPGLLSRAVQELRMIRTGRNDVEREVFDITTGKFTVEKTAQDNVMHRVIPKTAIRNTSGMINDALNNLDQEGQLSPAARKALSERLLRDASTNRRFDPNAYIRAGGYADGLSPDVTN...,2319,0
2,EN4815120|C|Q8SCY1|phage phiKZ lysin,MAKKVTLPKGQTGATGTTLGQAGNILDLSDVDDIFGDTPKAKKGSPVTEFFNGIKQGLFDSVKPQQALKAFMRSAAPDGFSRMFGVYEDTMSTIRDVKDSVERTSASDLLFLTREAQDLAVKLKDKVPASVFDRLNNRLESQIENYKYAEDSNRNYKEIRRRMEAERDEDELKSAIDQVTLVQRDLAIKAEQGEVKRFAIGQAERGIRDKVSADRFDWMAKAMGQTVDNLSKLASYNEQVNYSIQKKGLEIQFRSMLHLRKIAQQTEATMELLNNGFAALVRNTGIPDHKKSSMKDLVGFNAAQRVSSSFVDNAIQTLPNFLGNFGSAVTNNATRFANENIRNFADAVRAGNMFGADAWENRYNIAGQFAGSYLGDWTRNSVIPVLGRMARPGIERFSNNYLGGRHNQASYLLDNFPAWTQEYMNNYQNTYGARGILRDIMAPFIPQFTLQDRLKTGSYQTIGQDSGFNQLTQRTIVEAIPGYLSRLLQETRMIRTGRDDITREVFDLSTGSFMSVEDSAANTERRLVSRSTVRGVSGALTDVLEAFDPNKELSIDARKALTERLIRDANMNKRFDPEAYARAGGYDRSKVSGETI...,2237,0
3,EN3016141|D|D2J8A7|bacteriocin,MAETIKGLRIDLSLKDMGVGRSITELKRSFRTLNSDLKVSSKNFEYTEKSTQSYKRRLEELGSAVKVATKNVEALENEYHTVAEAQGHNSKQAQALRAEYNRQATELKFLQDSLNDTTQDYKEFTKAQQIANSGWTKAGNGMTSISKGLDSVSNKLSSTGQSLTNSITKPALIAGGALAGMTAKLGFDRLVGLDSAKAKLEGLGKSTEEVERISKQVANGIKGGMTTMAEGTDVAAGALASGVKEGKELEKYIKLVGDASVGANRPVADMAMIFNRVTGQGKLMTEELNMVEEGMPGFSKAMAKHLGVTYEEFRKMVTEGQVSSKDFMTVMEDFAGNMSGAYAKSFKGMWQNSKAYIGMIGESLLSGAFEQSKDSLREFEKLLQSPGAQQWAKETGEKLATGIEKISSAISGIISWFNSLDKGTQKSIASIMKWSTLILIGIGPVLTIFGKLTGVLAGTFGGLGKVLGFMGKLSTETKNAGSLLGGFTKLFPKLGGAIGLVANPIGLTVLAIGALVAGLVIAYKKSETFRNIVNGAFNAIVTGLSALWNGIKTFLQPVIKAITDFGGELKKTIGDFWAENGAQFMQALSNIKNAFI...,1619,0
4,EN9175723|BD|Q93IM3|bacteriocin,MAKKKNTYKVPSIIALTLAGTALTTHHAQAADKTQDQSTNKNILNDDKALNQSEQIKSEISKPTANISGTQVYKDPTQIKQASTDNNLNYDAQIDELNNQTSDQMTTQNTYNQNGQDQEAQQKDDSTVKTNQENVENEITSDEATNNVNTSDNVEKQATEAVQNDSVVTDKDDVTSNDSQDVAKDINKFDDTSVEQDNNAVQNDSVVTDKDDVTSNDSQDVTKDSDKSDAASSEQGNNAVQNDSVVTDKDDVTSNDSQDVTKDSDKSDATSNEQDSNAVQQDNSASDKDDVTSDDSQDVAKDSVKSDAASNEQDSNAVQNGSAVTDKDDVISDDSQDVAKDSVKSDAASNEQDSNAVQKDDSTSDIDDVTSDDSQDVAKDSVKSDATSSEQDSNAVQKDDSTSDKDDVTSDDSQDVAKDSVKSDDASNEQDSNAVQKDDIASDKDDVTSDDSQDVAKDSDKSDATSTKQDSNTVQQDDSTSDKDDVTSDDSQDVAKDSDKSDAASSEQDTEALQQDDSTSDKDDVTSDDSQDVTKDSDKSDAASTKQDSNTVQKDGAETTKAVNTTFYSAQAAPKLRVARSADSTVATRSALTKET...,1564,0
...,...,...,...,...
41946,UniRef50_B2ABU5 Podospora anserina S mat+ genomic DNA chromosome 2 supercontig 1 (Fragment) n=1 Tax=Podospora anserina (strain S / ATCC MYA-4624 / DSM 980 / FGSC 10383) TaxID=515849 RepID=B2ABU5_PODAN,MKWKAIIAAYGM,12,1
41947,UniRef50_A0A151HEL5 Zinc finger C3HC4 type (RING finger) domain-containing protein (Fragment) n=1 Tax=Toxoplasma gondii TgCatPRC2 TaxID=1130821 RepID=A0A151HEL5_TOXGO,GLYFRPRRRASS,12,1
41948,UniRef50_K2MU79 Retrotransposon hot spot (RHS) protein putative n=1 Tax=Trypanosoma cruzi marinkellei TaxID=85056 RepID=K2MU79_TRYCR,MESNPMTLVGCG,12,1
41949,UniRef50_A0A1E1IUT2 Flagellar calcium-binding protein putative (Fragment) n=1 Tax=Leishmania guyanensis TaxID=5670 RepID=A0A1E1IUT2_LEIGU,IRCVGHWMQAEH,12,1
41950,UniRef50_A0A0S4ITT4 Dopa decarboxylase putative (Fragment) n=1 Tax=Bodo saltans TaxID=75058 RepID=A0A0S4ITT4_BODSA,APWSASTLHCPG,12,1

In [26]:
#query_list = df["seq"]
#training_AMPs_df[training_AMPs_df['Sequence'].isin(query_list)]

,ID,Sequence,length,class
15427,"AP02705|ISGCock_Contig05_0593 (insects, arthropods, invertebrates, animals, UCLL1)",MKTFLRLYRSLINKVLHV,18,0

# Predict on Shuffled sequences

In [14]:
df= pd.read_pickle("../datasets/truthset/AMPs_truthset_42.reps.plk")

In [15]:
def predict(_df):
    #df = _df.loc[_df.length > 70 ].copy()
    #df = _df.loc[_df.length <= 30 ].copy()
    df = _df
    print(len(df))
    ready_df =df[[ "reps"]]
    df_new = ready_df.reps.apply(pd.Series).astype(np.float64)
    df_new.columns = df_new.columns.astype(str)
    dl = learner.dls.test_dl(df_new)
    _preds,_none ,_y = learner.get_preds(dl=dl, with_decoded=True)
    df['class'] = _y
    df.drop(columns=['reps'],inplace =True)
    accuracy = (len(df[df["class"] == 1])/len(df) )*100
    print("predict AMP :"+str(len(df[df["class"] == 0])))
    print("predict NonAMP:"+str(len(df[df["class"] == 1])))
    print("predict NonAMP (in percentage):"+str(accuracy))

In [16]:
df = pd.read_pickle("../datasets/truthset/AMPs_truthset_42.reps.plk")
predict(df)

62

predict AMP :37
predict NonAMP:25
predict NonAMP (in percentage):40.32258064516129

In [17]:
df = pd.read_pickle("../datasets/truthset/AMPs_truthset_43.reps.plk")
predict(df)

62

predict AMP :31
predict NonAMP:31
predict NonAMP (in percentage):50.0

In [19]:
df = pd.read_pickle("../datasets/truthset/AMPs_truthset_44.reps.plk")
predict(df)

62

predict AMP :39
predict NonAMP:23
predict NonAMP (in percentage):37.096774193548384

In [20]:
df = pd.read_pickle("../datasets/truthset/AMPs_truthset_45.reps.plk")
predict(df)

62

predict AMP :38
predict NonAMP:24
predict NonAMP (in percentage):38.70967741935484

In [21]:
df = pd.read_pickle("../datasets/truthset/AMPs_truthset_46.reps.plk")
predict(df)

62

predict AMP :36
predict NonAMP:26
predict NonAMP (in percentage):41.935483870967744

In [22]:
df = pd.read_pickle("../datasets/truthset/AMPs_truthset_47.reps.plk")
predict(df)

62

predict AMP :31
predict NonAMP:31
predict NonAMP (in percentage):50.0

In [24]:
df = pd.read_pickle("../datasets/truthset/AMPs_truthset_48.reps.plk")
predict(df)

62

predict AMP :38
predict NonAMP:24
predict NonAMP (in percentage):38.70967741935484

In [23]:
df = pd.read_pickle("../datasets/truthset//AMPs_truthset_49.reps.plk")
predict(df)

62

predict AMP :40
predict NonAMP:22
predict NonAMP (in percentage):35.483870967741936

In [25]:
df = pd.read_pickle("../datasets/truthset//AMPs_truthset_50.reps.plk")
predict(df)

62

predict AMP :37
predict NonAMP:25
predict NonAMP (in percentage):40.32258064516129

In [26]:
df = pd.read_pickle("../datasets/truthset//AMPs_truthset_51.reps.plk")
predict(df)

62

predict AMP :40
predict NonAMP:22
predict NonAMP (in percentage):35.483870967741936

Ten times

In [27]:
df = pd.read_pickle("../datasets/truthset/AMPs_truthset_10times.reps.plk")
predict(df)

62

predict AMP :40
predict NonAMP:22
predict NonAMP (in percentage):35.483870967741936